# Sale Prediction

In [18]:
import pandas as pd
import numpy as np
from datetime import datetime, date

In [19]:
# load data
categories = pd.read_csv("item_categories.csv")
items = pd.read_csv("items.csv")
shops = pd.read_csv("shops.csv")
test = pd.read_csv("test.csv")
train = pd.read_csv("sales_train.csv")

From the competition, it wants the final result to be item id and the item count per month. The prediction primarly depends on the shop_id and item_id and item_cnt_day. Firstly, we need to clean the data.

In [22]:
# We wish to find the number of sale per month
train["month"] = train["date"].apply(lambda x: datetime.strptime(x, '%d.%m.%Y').strftime('%m'))
train["year"] = train["date"].apply(lambda x: datetime.strptime(x, '%d.%m.%Y').strftime('%Y'))

In [24]:
train = train.drop(columns=['date_block_num'])

In [28]:
train

               date  shop_id  item_id  item_price  item_cnt_day month  year
0        02.01.2013       59    22154      999.00           1.0    01  2013
1        03.01.2013       25     2552      899.00           1.0    01  2013
2        05.01.2013       25     2552      899.00          -1.0    01  2013
3        06.01.2013       25     2554     1709.05           1.0    01  2013
4        15.01.2013       25     2555     1099.00           1.0    01  2013
5        10.01.2013       25     2564      349.00           1.0    01  2013
6        02.01.2013       25     2565      549.00           1.0    01  2013
7        04.01.2013       25     2572      239.00           1.0    01  2013
8        11.01.2013       25     2572      299.00           1.0    01  2013
9        03.01.2013       25     2573      299.00           3.0    01  2013
10       03.01.2013       25     2574      399.00           2.0    01  2013
11       05.01.2013       25     2574      399.00           1.0    01  2013
12       07.01.2013       25     2574      399.00           1.0    01  2013
13       08.01.2013       25     2574      399.00           2.0    01  2013
14       10.01.2013       25     2574      399.00           1.0    01  2013
15       11.01.2013       25     2574      399.00           2.0    01  2013
16       13.01.2013       25     2574      399.00           1.0    01  2013
17       16.01.2013       25     2574      399.00           1.0    01  2013
18       26.01.2013       25     2574      399.00           1.0    01  2013
19       27.01.2013       25     2574      399.00           1.0    01  2013
20       09.01.2013       25     2593      279.00           1.0    01  2013
21       16.01.2013       25     2604      299.00           1.0    01  2013
22       27.01.2013       25     2604      299.00           1.0    01  2013
23       27.01.2013       25     2607      279.00           1.0    01  2013
24       29.01.2013       25     2607      279.00           1.0    01  2013
25       27.01.2013       25     2609     1699.00           1.0    01  2013
26       06.01.2013       25     2548     1708.95           1.0    01  2013
27       26.01.2013       25     2611      299.00           1.0    01  2013
28       02.01.2013       25     2546      299.00           1.0    01  2013
29       06.01.2013       25     2515     1649.00           1.0    01  2013
...             ...      ...      ...         ...           ...   ...   ...
2935819  16.10.2015       25     7789     1799.00           1.0    10  2015
2935820  22.10.2015       25     7790      799.00           1.0    10  2015
2935821  22.10.2015       25     7791      899.50           1.0    10  2015
2935822  17.10.2015       25     7632     2310.00           1.0    10  2015
2935823  26.10.2015       25     7487      299.00           1.0    10  2015
2935824  14.10.2015       25     7029      999.00           1.0    10  2015
2935825  23.10.2015       25     7460      299.00           1.0    10  2015
2935826  04.10.2015       25     7233      599.00           1.0    10  2015
2935827  18.10.2015       25     7308      349.00           1.0    10  2015
2935828  21.10.2015       25     7233      479.00           1.0    10  2015
2935829  03.10.2015       25     7233      599.00           1.0    10  2015
2935830  11.10.2015       25     7286      299.00           1.0    10  2015
2935831  22.10.2015       25     7187      299.00           1.0    10  2015
2935832  26.10.2015       25     7484      299.00           1.0    10  2015
2935833  22.10.2015       25     7308      349.00           1.0    10  2015
2935834  29.10.2015       25     7235      298.00           1.0    10  2015
2935835  18.10.2015       25     7327      349.00           1.0    10  2015
2935836  22.10.2015       25     7327      349.00           1.0    10  2015
2935837  24.10.2015       25     7328      249.00           1.0    10  2015
2935838  17.10.2015       25     7338      349.00           1.0    10  2015
2935839  24.10.2015       25     7315      399.00           1.0    10  2015
2935840  31.10.2015       25     7409      299.00           1.0    10  2015
2935841  11.10.2015       25     7393      349.00           1.0    10  2015
2935842  10.10.2015       25     7384      749.00           1.0    10  2015
2935843  09.10.2015       25     7409      299.00           1.0    10  2015
2935844  10.10.2015       25     7409      299.00           1.0    10  2015
2935845  09.10.2015       25     7460      299.00           1.0    10  2015
2935846  14.10.2015       25     7459      349.00           1.0    10  2015
2935847  22.10.2015       25     7440      299.00           1.0    10  2015
2935848  03.10.2015       25     7460      299.00           1.0    10  2015

[2935849 rows x 7 columns]